(function() {var implementors = {};
implementors['vec_map'] = ["impl&lt;V: <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='vec_map/struct.VecMap.html' title='vec_map::VecMap'>VecMap</a>&lt;V&gt;","impl&lt;'a, V&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='vec_map/struct.Iter.html' title='vec_map::Iter'>Iter</a>&lt;'a, V&gt;","impl&lt;'a, V&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='vec_map/struct.Keys.html' title='vec_map::Keys'>Keys</a>&lt;'a, V&gt;","impl&lt;'a, V&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='vec_map/struct.Values.html' title='vec_map::Values'>Values</a>&lt;'a, V&gt;",];implementors['obj'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='obj/raw/object/enum.Line.html' title='obj::raw::object::Line'>Line</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='obj/raw/object/enum.Polygon.html' title='obj::raw::object::Polygon'>Polygon</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='obj/raw/object/struct.Group.html' title='obj::raw::object::Group'>Group</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='obj/raw/object/struct.Range.html' title='obj::raw::object::Range'>Range</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='obj/raw/material/struct.RawMtl.html' title='obj::raw::material::RawMtl'>RawMtl</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='obj/struct.Vertex.html' title='obj::Vertex'>Vertex</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='obj/struct.Position.html' title='obj::Position'>Position</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
